package com.cafeoccidente.backend.purchases.drycoffee.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

public record DryCoffeePurchaseResponse(
        Long id,
        LocalDate purchaseDate,
        Long agencyId,
        String agencyName,
        Long fundId,
        String fundCode,
        String specialType,
        String productCode,
        String announcementNumber,
        LocalDate announcementDate,
        BigDecimal basePriceLoad,
        String idNumber,
        String firstName,
        String lastName,
        String growerType,
        String address,
        String cellphone,
        Integer bagsCount,
        BigDecimal grossKg,
        BigDecimal tareKg,
        BigDecimal netKg,
        BigDecimal totalStoredWeight,
        BigDecimal wastePercentage,
        BigDecimal defectiveStoredWeight,
        BigDecimal defectivePercentage,
        BigDecimal healthyStoredWeight,
        BigDecimal healthyPercentage,
        BigDecimal healthyUnitPrice,
        BigDecimal defectiveUnitPrice,
        BigDecimal bonus,
        BigDecimal penalty,
        BigDecimal costs,
        BigDecimal unitPrice,
        BigDecimal grossValue,
        BigDecimal inventoryValue,
        BigDecimal associateContribution,
        BigDecimal cooperativeDiscount,
        boolean withholdingExempt,
        BigDecimal withholding,
        BigDecimal freightDiscount,
        BigDecimal otherDiscounts,
        BigDecimal netToPay,
        String paymentMethod,
        String checkNumber,
        Long createdByUserId) {
}
